name: fincalc_india
description: Smart financial calculators for India.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  share_plus: ^13.3.0
  google_mobile_ads: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: assets/icon/play_store_icon_512.png
  adaptive_icon_background: "#07154F"
  adaptive_icon_foreground: assets/icon/play_store_icon_512.png

flutter:
  uses-material-design: true
